name: serbia_open_data_explorer
description: "Serbia Open Data Explorer"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.7

dependencies:
  csv: ^6.0.0
  flutter:
    sdk: flutter
  path: ^1.9.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/datasets/datasets.csv
